#!/usr/bin/python3
# qubes-task-gui.py

# TODO following imports somehow needed for execution already built pyinstaller exe
from __future__ import print_function
import xml.etree.ElementTree
import glob
import numbers
import ast
# TODO end of imports which are required by pyinstaller exe

import subprocess
import sys

import json

from unman_repo_installaton import install_repo_3isec, is_inited_repo_3isec


# Following code ensure that pyinstaller exe use exact needed imports
def append_system_libs():
    # execute the "python3 -c 'import site; print(json.dumps(site.getsitepackages()))'" command and capture the output
    result = subprocess.run(["python3", "-c", "import site, json; print(json.dumps(site.getsitepackages()))"],
                            stdout=subprocess.PIPE)

    # extract the output from the result and parse it as JSON
    output = json.loads(result.stdout)
    # append each path to sys.path
    for path in output:
        sys.path.append(path)


# let's use all libraries from the client to ensure maximum compatibility
append_system_libs()

from PyQt5 import QtWidgets, QtGui, uic
from PyQt5.QtWidgets import (
    QWidget, QApplication, QButtonGroup, QHBoxLayout, QVBoxLayout,
    QCheckBox, QLabel, QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSpacerItem, QTabWidget)

from PyQt5.QtCore import QObject, Qt, pyqtSignal, QProcess
from PyQt5.QtGui import QPainter, QFont, QColor, QPen
# from row import TaskRowWidget
from qubes_task import *
from qubesadmin.tools.qvm_template import Template as Task

appl = qubesadmin.Qubes()
args = ['dict']
p_args, args = parser.parse_known_args(args)
p_args = parser.parse_args(args, p_args)
p_args.repo_files = REPO_FILE
p_args.updatevm = appl.updatevm


class TaskRowWidget(QWidget):

    def __init__(self, parent, name, summary):
        super(TaskRowWidget, self).__init__()
        self.parent = parent
        self.name = name  # Name of widget used for searching.
        self.summary = summary
        self.is_on = False

        self.setAccessibleName = name
        self.lbl2 = QLabel(self.summary)
        self.checked = QCheckBox(self.name)
        parent.taskGroup.addButton(self.checked)
        self.btn_details = QPushButton("Details")
        self.btn_details.setAccessibleName(name)
        self.btn_details.setCheckable(False)
        self.btn_details.clicked.connect(parent.details_clicked)

        self.hbox = QHBoxLayout()
        self.hbox.addWidget(self.checked, 20)
        self.hbox.addWidget(self.lbl2, 60)
        self.hbox.addWidget(self.btn_details)
        self.setLayout(self.hbox)


class MainWindow(QMainWindow):

    def __init__(self, command='dict', *args, **kwargs):
        super().__init__()

        self.tabWidget = QTabWidget()
        # Create tabs
        self.tabOverview = QWidget()
        self.tabTasks = QWidget()

        # Add tabs to the tab widget
        self.tabWidget.addTab(self.tabOverview, "Overview")
        self.tabWidget.addTab(self.tabTasks, "Tasks")

        # Tab overview
        v_layout_overview = QVBoxLayout()
        label = QLabel("Task manager")
        v_layout_overview.addWidget(label)
        self.tabOverview.setLayout(v_layout_overview)

        # Tab tasks
        self.tasksLayout = QVBoxLayout()  # Tasks container layout.
        self.taskGroup = QButtonGroup()
        self.taskGroup.setExclusive(False)

        self.is_3isec_repo_inited = is_inited_repo_3isec()

        if self.is_3isec_repo_inited:
            self.get_repos()
            self.widgets = []
            for name in self.widget_names:
                detail = self.outputs[name]['summary']
                item = TaskRowWidget(self, name, detail)
                self.tasksLayout.addWidget(item)
                self.widgets.append(item)
            spacer = QSpacerItem(1, 1, QSizePolicy.Minimum, QSizePolicy.Expanding)
            self.tasks = QWidget()
            self.tasksLayout.addItem(spacer)
            self.tasks.setLayout(self.tasksLayout)
            self.lbl = QLabel(""" Description
                    """)
            self.lbl.setAlignment(Qt.AlignTop)
            # Scroll Area Properties.
            self.scroll = QScrollArea()
            self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
            self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
            self.scroll.setWidgetResizable(True)
            self.scroll.setWidget(self.tasks)

            self.scroll2 = QScrollArea()
            self.scroll2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
            self.scroll2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
            self.scroll2.setWidgetResizable(True)
            self.scroll2.setWidget(self.lbl)

            self.searchbar = QLineEdit()
            self.btn_install = QPushButton("Install")
            self.btn_install.setCheckable(False)
            self.btn_install.clicked.connect(self.install_tasks)

            # Add the items to VBoxLayout (applied to container widget)
            # which encompasses the whole window.
            containerLayout = QVBoxLayout()
            # containerLayout.addWidget(self.searchbar)
            containerLayout.addWidget(self.btn_install)
            containerLayout.addWidget(self.scroll, 60)
            containerLayout.addWidget(self.scroll2, 40)
            self.tabTasks.setLayout(containerLayout)
        else:
            text = """The repository definition is:

            [3isec-dom0-current]
            name = 3isec Qubes Dom0 Repository (updates)
            baseurl = https://qubes.3isec.org/rpm/r$releasever/current/dom0/fc32
            skip_if_unavailable=False
            enabled = 1
            metadata_expire = 6h
            gpgcheck = 1
            gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-unman

            Create a file in dom0 with this content at /etc/yum.repos.d/3isec-dom0.repo

            All packages are signed with my Qubes OS Signing key.
            You'll need to get this from a keyserver, or two, to make sure all is fine:
            keyserver.ubuntu.com or pgp.mit.edu

            You can also check the Qubes users mailing list or look on github.

            Once you have copies of the key, check the fingerprint:

            gpg -n --import --import-options import-show unman.pub

            replacing unman.pub with the path to the key.
            The output should look similar to this:

            pub   rsa4096 2016-06-25 [SC]
                  4B1F 400D F256 51B5 3C41  41B3 8B3F 30F9 C8C0 C2EF
            uid           [ unknown] unman (Qubes OS signing key) 
            sub   rsa4096 2016-06-27 [S] [expires: 2024-06-30]
            sub   rsa4096 2016-06-25 [E]

            In particular, check that the output from your command contains the fingerprint 4B1F 400D F256 51B5 3C41 41B3 8B3F 30F9 C8C0 C2EF

            When you are happy, copy the key in to dom0:

            qvm-run -p QUBE_WHERE_YOU_DOWNLOADED_KEY 'cat PATH_TO_KEY' > RPM-GPG-KEY-unman
            sudo mv RPM-GPG-KEY-unman /etc/pki/rpm-gpg/
            """
            layout = QVBoxLayout()

            # Create QLabel instance with some text
            label = QLabel(text)
            label.setAlignment(Qt.AlignCenter)  # Align text to the center

            # Create QPushButton instances for OK and Cancel
            button_ok = QPushButton('OK')

            def accept():
                install_repo_3isec()

            # Connect buttons to the appropriate slots (functions)
            button_ok.clicked.connect(accept)  # built-in QDialog function to accept (OK) the dialog

            # Add the QLabel and QPushButtons to the layout
            layout.addWidget(label)
            layout.addWidget(button_ok)

            self.tabTasks.setLayout(layout)

        self.setCentralWidget(self.tabWidget)

        self.setGeometry(600, 100, 900, 600)
        self.setWindowTitle('Qubes Task Manager')
        self.setWindowIcon = QtGui.QIcon.fromTheme("qubes-manager")

    def get_repos(self):
        self.outputs = {}
        self.outputs = list_tasks(p_args, appl, 'dict')
        self.widget_names = self.outputs.keys()

    def details_clicked(widget, state):
        sending_widget = widget.sender()
        name = (sending_widget.accessibleName())
        desc = widget.outputs[name]['description']
        w.lbl.setText(desc)

    def install_tasks(widget, state):
        update_cmd = "sudo qubes-dom0-update "
        prefix = "3isec-qubes-"
        checked_buttons = [i for i, button in enumerate(w.taskGroup.buttons()) if button.isChecked()]
        pkgs_to_install = []
        for i in checked_buttons:
            pkgs_to_install.append(prefix + w.taskGroup.buttons()[i].text())
        try:
            install_list = " ".join(pkgs_to_install)
            child = subprocess.Popen(update_cmd + install_list, shell=True)
            output = child.communicate()[0]
        except Exception as e:  # pylint: disable=broad-except
            # output = child.communicate()[0]
            return 1
        return 0


app = QtWidgets.QApplication(sys.argv)
w = MainWindow()
w.show()
sys.exit(app.exec_())
